Assignment 2 completed
fcc-hyd/moc-android pull request #23
Opened 2017-06-05 20:28 UTC by ansul90

Added journal file too

2017-06-05 22:41 UTC, vramana requested changes
The journal file should look like this 
https://raw.githubusercontent.com/fcc-hyd/moc-android/master/sampleJournal.md

2017-06-06 05:53 UTC, mallelapavank commented on ansul/Assignment 1/activity_main.xml
> +        android:background="@android:color/white"
you've set the background color to white but your text color is also white in this theme which makes the entered text invisible. please change your text color to black or any other contrast color

2017-06-06 05:54 UTC, mallelapavank commented on ansul/Assignment 1/activity_main.xml
> +        android:background="@android:color/white"
consider this change in your constraint layout that you will make next. dont make any changes here. I'm merging this now.

2017-06-06 05:59 UTC, mallelapavank commented on ansul/journal.md
> +Today learnt about layouts
like @vramana suggested your journal should be in this format: if any questions ask on gitter chatroom
https://raw.githubusercontent.com/fcc-hyd/moc-android/master/sampleJournal.md

2017-06-06 16:43 UTC, closed without merging